export const WOOD_FILL        = '#f5ede0';
export const WOOD_STROKE      = '#8b6914';
export const WOOD_STROKE_W    = 1.5;
export const SEPARATOR_FILL   = '#e8d5b0';
export const DIM_COLOR        = '#dc2626';
export const SHELF_FILL       = '#dcc89a';
export const SHELF_STROKE     = '#8b6914';
export const ROD_STROKE       = '#4b5563';
export const ROD_FILL         = '#9ca3af';
export const DRAWER_FILL      = '#f5ede0';
export const DRAWER_STROKE    = '#8b6914';
export const HANDLE_FILL      = '#a0a0a0';
export const HANDLE_STROKE    = '#666';
export const DOOR_FILL        = 'rgba(232,220,200,0.85)';
export const DOOR_STROKE      = '#8b6914';
export const SELECTION_COLOR  = '#3b82f6';
export const SNAP_THRESHOLD   = 8;   // px — distance de magnétisme
export const MIN_MODULE_W_PX  = 30;  // largeur minimale d'un module en px
